export const REGISTER_USER='REGISTER_USER'
export const REGISTER_FAIL='REGISTER_FAIL'

export const LOGIN_USER='LOGIN_USER'
export const LOGIN_FAIL='LOGIN_FAIL'

export const LOGOUT='LOGOUT'
//product
export const GET_PRODUCT_SUCCESS='GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL='GET_PRODUCT_FAIL'
export const UPPDATE_PRODUCT_SUCCESS='UPPDATE_PRODUCT_SUCCESS'
export const UPPDATE_PRODUCT_FAIL='UPPDATE_PRODUCT_FAIL'
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL='DELETE_PRODUCT_FAIL'
export const POST_PRODUCT_SUCCESS='POST_PRODUCT_SUCCESS'
export const POST_PRODUCT_FAIL='POST_PRODUCT_FAIL'
//category
export const GET_CATEGORY_SUCCESS='GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAIL='GET_CATEGORY_FAIL'
export const UPPDATE_CATEGORY_SUCCESS='UPPDATE_CATEGORY_SUCCESS'
export const UPPDATE_CATEGORY_FAIL='UPPDATE_CATEGORY_FAIL'
export const DELETE_CATEGORY_SUCCESS='DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAIL='DELETE_CATEGORY_FAIL'
export const POST_CATEGORY_SUCCESS='POST_PRODUCT_SUCCESS'
export const POST_CATEGORY_FAIL='POST_CATEGORY_FAIL'
export const  GET_ITEM='GET_ITEM'
//commande

export const ADD_COMMANDE_FAIL="ADD_COMMANDE_FAIL"
export const ADD_COMMANDE_SUCCESS="ADD_COMMANDE_SUCCESS"
export const DELETE_COMMANDE_FAIL="DELETE_COMMANDE_FAIL"
export const DELETE_COMMANDE_SUCCESS="DELETE_COMMANDE_SUCCESS"
export const UPDATE_COMMANDE_FAIL="UPDATE_COMMANDE_FAIL"
export const UPDATE_COMMANDE_SUCCESS="UPDATE_COMMANDE_SUCCESS"
export const GET_COMMANDE_FAIL="GET_COMMANDE_FAIL"
export const GET_COMMANDE_SUCCESS="GET_COMMANDE_SUCCESS"