export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const UPDATE_USER='UPDATE_USER'
export const UPDATE_FAIL='UPDATE_FAIL'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'
//product
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS'
export const POST_PRODUCT_FAIL = 'POST_PRODUCT_FAIL'
//theme
export const GET_THEME_SUCCESS = 'GET_THEME_SUCCESS'
export const GET_THEME_FAIL = 'GET_THEME_FAIL'
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS'
export const UPDATE_THEME_FAIL = 'UPDATE_THEME_FAIL'
export const DELETE_THEME_SUCCESS = 'DELETE_THEME_SUCCESS'
export const DELETE_THEME_FAIL = 'DELETE_THEME_FAIL'
export const POST_THEME_SUCCESS = 'POST_THEME_SUCCESS'
export const POST_THEME_FAIL = 'POST_THEME_FAIL'
//category
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL'
export const UPPDATE_CATEGORY_SUCCESS = 'UPPDATE_CATEGORY_SUCCESS'
export const UPPDATE_CATEGORY_FAIL = 'UPPDATE_CATEGORY_FAIL'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL'
export const POST_CATEGORY_SUCCESS = 'POST_PRODUCT_SUCCESS'
export const POST_CATEGORY_FAIL = 'POST_CATEGORY_FAIL'
export const GET_ITEM = 'GET_ITEM'
//commande

export const ADD_COMMANDE_FAIL = "ADD_COMMANDE_FAIL"
export const ADD_COMMANDE_SUCCESS = "ADD_COMMANDE_SUCCESS"
export const DELETE_COMMANDE_FAIL = "DELETE_COMMANDE_FAIL"
export const DELETE_COMMANDE_SUCCESS = "DELETE_COMMANDE_SUCCESS"
export const UPDATE_COMMANDE_FAIL = "UPDATE_COMMANDE_FAIL"
export const UPDATE_COMMANDE_SUCCESS = "UPDATE_COMMANDE_SUCCESS"
export const GET_COMMANDE_FAIL = "GET_COMMANDE_FAIL"
export const GET_COMMANDE_SUCCESS = "GET_COMMANDE_SUCCESS"
export const VALIDATE_COMMANDE_SUCCESS = "VALIDATE_COMMANDE_SUCCESS"
export const VALIDATE_COMMANDE_FAIL = "VALIDATE_COMMANDE_FAIL"
//ligne commande
export const ADD_LIGNECOMMANDE_SUCCESS = "ADD_LIGNECOMMANDE_SUCCESS"
export const GET_LIGNECOMMANDE_SUCCESS = "GET_LIGNECOMMANDE_SUCCESS"
export const UPDATE_LIGNECOMMANDE_SUCCESS= "UPDATE_LIGNECOMMANDE_SUCCESS"
export const DELETE_LIGNECOMMANDE_SUCCESS = "DELETE_LIGNECOMMANDE_SUCCESS"
export const ADD_LIGNECOMMANDE_FAIL = "ADD_LIGNECOMMANDE_FAIL"
export const GET_LIGNECOMMANDE_FAIL = "GET_LIGNECOMMANDE_FAIL"
export const UPDATE_LIGNECOMMANDE_FAIL = "UPDATE_LIGNECOMMANDE_FAIL"
export const DELETE_LIGNECOMMANDE_FAIL = "DELETE_LIGNECOMMANDE_FAIL"

//client
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FAIL="GET_USER_FAIL"


export const CART_ADD_ITEM="CART_ADD_ITEM"
export const CART_REMOVE_ITEM="CART_REMOVE_ITEM"
export const CART_ADD_ITEM_FAIL="CART_ADD_ITEM_FAIL"

export const CATEGORY_GET_ITEM="CATEGORY_GET_ITEM"